services:
  cfn:
    image: ghcr.io/k-wojciechowski/cleanupfornotion:latest
    ports:
      - 127.0.0.1:2836:2836
    environment:
      CleanupForNotion__StateFilePath: /app/cfnstate.json
      ASPNETCORE_URLS: "http://0.0.0.0:2836"
    user: "33:33" # www-data on Debian-like systems
    volumes:
      - ./appsettings.json:/app/appsettings.json
      - ./cfnstate.json:/app/cfnstate.json
